spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kozmotr/config-server/
          clone-on-start: true
        default-label: main
  application:
    name: CONFIG-SERVER

server:
  port: 9296